### ISSUE TITLE
Populating repo

### ISSUE THREAD

**Issue by hbbtstar** [segment-integrations/analytics.js-integration-parsely#1]
Can somebody put a readme or something in here so I can issue a pull request? Thanks!

**Comment by f2prateek** [comment]
ping @ndhoule , is there a template we can drop in here?

**Comment by hbbtstar** [comment]
I was given a template I adapted for us, so that's OK, I just can't issue a PR to an empty repo (unless I'm missing that option somewhere)

**Comment by ndhoule** [comment]
@hbbtstar nah, you're right—GitHub won't let you PR without an initial commit, for whatever reason. Done.
