### ISSUE TITLE
apikey option doesn't seem to be populating on site

### ISSUE THREAD

**Issue by hbbtstar** [segment-integrations/analytics.js-integration-parsely#6]
Hi!

So we have a client that is trying to integrate with segment, and the api option field doesn't appear to be passing correctly.

I tried it with my own personal site to duplicate the issue, and here's what I found:

![elevatedtodayapikey](https://cloud.githubusercontent.com/assets/3144867/8577697/c466eb1e-25aa-11e5-9006-c3a1b712a50e.png)

if I am understanding correctly, should pass an option that this line then picks up:

https://github.com/segment-integrations/analytics.js-integration-parsely/blob/master/lib/index.js#L25-L27

which is the behavior I see in the tests that are passing. However, when live it appears to be blank and this is the <meta> tag that comes back:

    <meta data-parsely-site="" id="parsely-cfg">

am I using this.options.apiKey incorrectly? Based on looking at other integrations it seems that it should work, but perhaps I'm missing something that you guys can see.

Thanks for all the help!

**Comment by hankim813** [comment]
@hbbtstar is this still an issue?

**Comment by hbbtstar** [comment]
hi @hankim813!

I don't believe it is, this is an old ticket- the problem was resolved, though I don't remember when. I'm going to go ahead and close this, thanks for checking in!
